framework:
  secret: '%env(APP_SECRET)%'
  default_locale: ru
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - ru
      - en
  http_method_override: false
  handle_all_throwables: true
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
  validation:
    email_validation_mode: html5
  serializer:
    enabled: true
  router:
    utf8: true
