framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true
  session: false
  validation:
    email_validation_mode: html5
  serializer:
    enabled: true
  router:
    utf8: true
