map $http_x_forwarded_proto $fcgi_forwarded_proto {
    default $http_x_forwarded_proto;
    ''      $scheme;
}

map $http_x_forwarded_host $fcgi_forwarded_host {
    default $http_x_forwarded_host;
    ''      $host;
}

map $http_x_forwarded_for $fcgi_forwarded_for {
    default $http_x_forwarded_for;
    ''      $remote_addr;
}

map $http_x_forwarded_port $fcgi_forwarded_port {
    default $http_x_forwarded_port;
    ''      $server_port;
}

server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param HTTP_X_FORWARDED_PROTO $fcgi_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $fcgi_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_FOR $fcgi_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PORT $fcgi_forwarded_port;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
